### ISSUE TITLE
Conclusions of the meeting with Benny Zend and Shani Cohab Levy 18.11.18

### ISSUE THREAD

**Issue by IlanKro** [SCE-SWE-2018-G3/ticket-management-system#21]
General:
-There are a lot of misunderstanding and lack comprehension about a lot of matters about this project between the group members.
We should ALL be in line on what's the details of the system and agree on them.
SRS:
We got 92 in the SRS and prototype but there are still a few points they really push on:
1.They want us to have a severity system rating, define what each level mean do note that it doesn't matter for the system, for whom the problem raised not even if it's the CEO, so basically we have levels according to the amount of users it affects, no need for LSA.
2.Also they want a reporting system for the sake of analysis I see it as a "stats" page only the team leader can see (or all, they just don't care) which gathers data, I don't think it needs to have it's own database, but get it's data from the ticket database.

DFD and Design:
1. We must really be sure we don't need another database.
2.They suggested we should add a field "from where is this ticket from:" phone call/mail/self service should also be added tot eh prototype and DFDs!!
3.Add the reporting system to the DFDs too.
4.Add more fields for the user and support giver to fill. (affects DFDs and code)
5. We should decide if we wanna drop the language support or not, they didn't seem too keen on the Hebrew language support.

Code: start coding basically they didn't comment on this.

**Comment by soryy708** [comment]
Not mentioned: Reduce free text inputs as much as possible. Select from drop-down menues.

**Comment by soryy708** [comment]
Hebrew language was voted out, and dropped in the following PR: https://github.com/SCE-SWE-2018-G3/ticket-management-system/pull/22

**Comment by soryy708** [comment]
@IlanKro Opened a cleaned-up issue just for the TODO:
https://github.com/SCE-SWE-2018-G3/ticket-management-system/issues/25
