### ISSUE TITLE
Implement customer menu business logic

### ISSUE THREAD

**Issue by soryy708** [SCE-SWE-2018-G3/ticket-management-system#23]

**Comment by IlanKro** [comment]
do be done until 09/12

**Comment by soryy708** [comment]
It should work.
You may have found a bug.

**Comment by soryy708** [comment]
https://github.com/SCE-SWE-2018-G3/ticket-management-system/pull/70

**Comment by soryy708** [comment]
OK, this was merged.

**Comment by soryy708** [comment]
@Ferayon @IlanKro @AlonGabbay 
Only one thing left here:
"List my support calls"

Please note that your deadline is over-due.

**Comment by soryy708** [comment]
https://github.com/SCE-SWE-2018-G3/ticket-management-system/pull/78
