### ISSUE TITLE
Update SRS, DFD, Prototype, Use Case, Design Document

### ISSUE THREAD

**Issue by soryy708** [SCE-SWE-2018-G3/ticket-management-system#25]
- Define a severity system. Define hat each level means. Not need for SLA.
- Add the "reporting system for the sake of analysis". "stats" page only support givers can see which gathers data.
- Add a field "from where is this ticket from:" (phone call/mail/self service)
- Perhaps add more fields for the user and support giver to fill?

**Comment by IlanKro** [comment]
I am stuck on the last part which fields do we want users to fill exactly.. severity.. and? TBH when I worked with self service CRM the user input was as minimal as we have it in the system adding severity to the user input will just make every user put "critical" there as any problem is critical to every person

**Comment by soryy708** [comment]
Which is why the customer does not input that.
Look in the prototype. There's a difference between a customer and support giver for a reason.

**Comment by IlanKro** [comment]
I know.. I sent shani a mail, explaining why there is no reason to expand that menu I will update the DFDs with the changes already made to prototype and SRS

**Comment by soryy708** [comment]
Main DFD -
1. missing label on arrow to `4. List Tickets` from `Support Givers`
2. `9. View statistics` arrow is confusing.
3. Make `D1 Tickets` more obvious that it's a db and not an long circular arrow

**Comment by soryy708** [comment]
DFD2  - stray circle

**Comment by soryy708** [comment]
DFD 2:
1. `Media of communication` sent by login!?
2. Stray circle

**Comment by soryy708** [comment]
Update the [https://github.com/SCE-SWE-2018-G3/ticket-management-system/blob/master/Documentation%20%26%20Design/ERD.png](ERD) with new data in ticket

**Comment by soryy708** [comment]
Continued there: https://github.com/SCE-SWE-2018-G3/ticket-management-system/issues/42
