### ISSUE TITLE
Sometimes when inputting things, some inputs are skipped.

### ISSUE THREAD

**Issue by soryy708** [SCE-SWE-2018-G3/ticket-management-system#32]
Maybe `scanf` overflows due to too small array?

Or maybe `scanf` stops because of ` ` (space) character. Meaning replace `wscanf` with `wgetline` or something.

**Comment by IlanKro** [comment]
To finish by 09/12

**Comment by IlanKro** [comment]
I checked the ticket creation by customer every input is skipped while pressing space, it takes every word as an argument.. This is a rather serious bug.. maybe we should make most of our menus more like the log in screen

**Comment by IlanKro** [comment]
https://stackoverflow.com/questions/53682684/widechar-in-c-skip-inputs
posted a question about this
I hope it doesn't get flagged as duplicate, since I didn't find an answer for this and this problem is consistent

**Comment by IlanKro** [comment]
I made a fix for this, I will upload it shortly, made a file to manage inputs input_manip.h please use this to get input in the future it makes the input much smoother.

**Comment by soryy708** [comment]
https://github.com/SCE-SWE-2018-G3/ticket-management-system/pull/70

**Comment by soryy708** [comment]
1. Look for places that do input without `input_manip`.
2. Look for related bugs via black-box testing.

**Comment by IlanKro** [comment]
We are working with this kind of input for a while.. seems to be working well.
