### ISSUE TITLE
Add API documentation in code

### ISSUE THREAD

**Issue by soryy708** [SCE-SWE-2018-G3/ticket-management-system#40]

**Comment by IlanKro** [comment]
BTW the API should be added on the header files I will try to add some tommrow, when someone write a function add API too.. it's important so we know how to use each function (the encapsulation principe)

**Comment by soryy708** [comment]
If I do my job correctly, no one should need to change any headers. If they do then only for trivial setters and getters.

**Comment by soryy708** [comment]
https://github.com/SCE-SWE-2018-G3/ticket-management-system/pull/54
