### ISSUE TITLE
Add tags criteria in the prototype on the support giver ticket creation

### ISSUE THREAD

**Issue by IlanKro** [SCE-SWE-2018-G3/ticket-management-system#42]
can't add it on ubuntu need someone with windows to add it.

**Comment by IlanKro** [comment]
Also change the ERD as well only add Communication media there, again can't change PPTX files in ubuntu it will run the file

**Comment by IlanKro** [comment]
Done

**Comment by soryy708** [comment]
https://github.com/SCE-SWE-2018-G3/ticket-management-system/pull/46
