### ISSUE TITLE
Implement reading and writing to database the notes

### ISSUE THREAD

**Issue by soryy708** [SCE-SWE-2018-G3/ticket-management-system#57]
[Reading notes happens here](https://github.com/SCE-SWE-2018-G3/ticket-management-system/blob/master/Source%20Code/Ticket%20Management%20System/ticket_container_util.c#L81)

[Writing notes happens here](https://github.com/SCE-SWE-2018-G3/ticket-management-system/blob/master/Source%20Code/Ticket%20Management%20System/ticket_container_util.c#L194)

We're working with [LeanSQL](https://github.com/soryy708/leansql) in a table based approach.

Consider - save the entire note in one table cell?
Or make a new table with a reference (in which case the documentation will need to be updated)

**Comment by StavLobel** [comment]
We came to a decision:
We'll be saving the notes as strings, not multiple fields. This means that there will be no Note struct in the code.
