### ISSUE TITLE
Add an analytical menu

### ISSUE THREAD

**Issue by IlanTulepov** [SCE-SWE-2018-G3/ticket-management-system#68]

**Comment by soryy708** [comment]
You mean the "status" page from the prototype?

**Comment by soryy708** [comment]
Discuss postponing to "version 2" ;)

**Comment by StavLobel** [comment]
Decided to postponing to V2 of app .
Need to change in Docs .

**Comment by soryy708** [comment]
Decision was made to not postpone in order to not risk grade reduction.

**Comment by soryy708** [comment]
1. Write the code
2. Update prototype based on written code

**Comment by IlanTulepov** [comment]
The analytical menu has been written and implemented, it is now waiting for the approval of the other team members.

**Comment by soryy708** [comment]
https://github.com/SCE-SWE-2018-G3/ticket-management-system/pull/87
