### ISSUE TITLE
When customer creates ticket, severity is (null)

### ISSUE THREAD

**Issue by soryy708** [SCE-SWE-2018-G3/ticket-management-system#71]

**Comment by IlanKro** [comment]
does the customer get to put severity in it?

**Comment by soryy708** [comment]
Check the documentation.
If not, then some default severity has to be set.

**Comment by IlanKro** [comment]
I found the problem it's in the customer menu.. there is no severity sending in there

**Comment by soryy708** [comment]
Will be fixed by https://github.com/SCE-SWE-2018-G3/ticket-management-system/issues/91
