### ISSUE TITLE
Customer menu - Update contact info - crash if inputting strings of characters

### ISSUE THREAD

**Issue by soryy708** [SCE-SWE-2018-G3/ticket-management-system#93]

**Comment by IlanKro** [comment]
we didn't exactly found the cause for the crash we only inputted very long strings in all fields... needs further inspections on this.. also it's not a critical bug since it's a wrong input I think it has to do with the length of one of the inputs.

**Comment by IlanKro** [comment]
I tested it.. it's specifically on the phone input..
I plan not to fix this bug cause I don't have time though.. it's not such a critical bug cause it works well with valid input.

**Comment by IlanKro** [comment]
If someone has time to do it.. you are welcome. it seems like a minor bug on how the data is sent.
